<?php

return [
    'PAGINATION_NUMBER' => 10,
    'NUMBER_OF_DAY_BETWEEN' => 30,
    'STATUS_OK' => 200,
    'STATUS_CREATED' => 201,
    'STATUS_BAD_REQUEST' => 400,
    'STATUS_FORBIDDEN' =>403,
    'STATUS_NOT_FOUND' => 404,
    'STATUS_INTERNAL_SERVER_ERROR' => 500
];

?>
